# Makefile for SGI systems (under IRIX)

.SUFFIXES: .c .o

# $S = ampl/solvers directory
S = ..

CC = cc
CFLAGS = -I$S -O
.c.o:
	$(CC) -c $(CFLAGS) $*.c

amplfunc.so: funcadd.o
	ld -shared -o amplfunc.so -soname amplfunc.so funcadd.o -lm

## Sample solver creation...

# $(myobjects) = list of .o files
myobjects = ....
LL = /usr/local/lib

mysolver: $(myobjects)
	$(CC) -o mysolver -L. -L$(LL) $(myobjects) $(LL)/amplfunc.so $S/amplsolver.a -lm
