name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Ubuntu-${{ matrix.ubuntu_version }}-mt-${{ matrix.mt }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: [20.04, 22.04]
        mt: [ON, OFF]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
                     
    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}" -DBUILD_MT_LIBS=${{ matrix.mt }} -DBUILD_CPP=ON -DBUILD_EXAMPLES=ON -DBUILD_F2C=ON -B "${{github.workspace}}/build" 

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  MSVC:
    name: windows-${{ matrix.win_version }}-mt-${{ matrix.mt }}
    runs-on: windows-${{ matrix.win_version }}
    strategy:
      fail-fast: false
      matrix:
        win_version: [2019, 2022]
        mt: [ON, OFF]

    steps:
      - name: Checkout
        uses: actions/checkout@v3   

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}" -DBUILD_MT_LIBS=${{ matrix.mt }} -DBUILD_CPP=ON -DBUILD_DYNRT_LIBS=ON -B "${{github.workspace}}/build" 

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  MinGW-w64:
    runs-on: windows-2022
    name: msys2-${{ matrix.msystem }}-mt-${{ matrix.mt }}
    strategy:
      fail-fast: false
      matrix:
        msystem: [UCRT64, CLANG64]
        mt: [ON, OFF]
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install MinGW-w64 packages
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          release: false
          update: true
          pacboy: >-
            cc:p
            cmake:p
            ninja:p
            openmp:p

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}" -DBUILD_MT_LIBS=${{ matrix.mt }} -DBUILD_CPP=ON -B "${{github.workspace}}/build"

      - name: Build
        run: cmake --build '${{github.workspace}}/build' --config ${{env.BUILD_TYPE}}
  macos:
    runs-on: macos-${{ matrix.macos_version }}
    name: macos-${{ matrix.macos_version }}
    strategy:
      fail-fast: false
      matrix:
        macos_version: [11, 12]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install OpenMP
        run: brew install libomp        
     
      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE="${{env.BUILD_TYPE}}" -DBUILD_CPP=ON -DBUILD_EXAMPLES=ON -DBUILD_F2C=ON -B "${{github.workspace}}/build"
        
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}